version: "3.7"
services:
  eventstore-node:
    image: eventstore/eventstore:release-5.0.2
    ports:
      - "1113:1113"
      - "2113:2113"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch